### ISSUE TITLE
Lenient http-spec

### ISSUE THREAD

**Issue by P0lip** [stoplightio/http-spec#30]
**Chore summary**
The low-level goal is to make http-spec treat malformed input in a more graceful manner.
The high-level goal is to improve UX in Studio, in particular when you open an existing spec that's incorrect.

**Tasks**
- [ ] upgrade to TS 3.7
- [ ] use `Optional<DeepPartial<actual shape>>` whenever possible
- [ ] drop all calls clobbering typings such as `lodash.get` and use optional chaining operator
- [ ] add a couple of tests covering edge cases

**Additional context**
Prettier uses outdated typescript/es-tree parser and won't parse optional chaining operator correctly.
For the time being, suggest turning off prettier rule in TSLint config until they upgrade it.

**Comment by P0lip** [comment]
`Optional<DeepPartial<actual shape>>` might be look tad controversial, therefore if you all think it's an overkill, we can stick with `DeepPartial<actual shape>`.

**Comment by chohmann** [comment]
@P0lip is this issue still relevant?

**Comment by P0lip** [comment]
Yeah, it's still relevant.
