### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by lottamus** [stoplightio/http-spec#63]
**Chore summary**
Let's help onboard new contributors to this repo by providing them with helpful documentation in the README 🤓 

**Tasks**
- [ ] Description of what this repo does and why it's important to Stoplight
- [ ] Outline of general architecture (accessors, transformers, etc)
- [ ] Outline of supported specs

**Additional context**
Feel free to go as detailed as you want. At the very least we can start with a good outline and fill out the important bits as we go.
