### ISSUE TITLE
Handle server URL comparison correctly

### ISSUE THREAD

**Issue by karol-maciaszek** [stoplightio/http-spec#84]
**Chore summary**
`IHttpOperation` [merger](https://github.com/stoplightio/http-spec/blob/master/src/merge.ts) does not handle all the cases for comparison of server URLs.

**Tasks**
- [ ] host should be compared as case-insensitive
- [ ] path should be compared as case-sensitive
- [ ] variable names should be compared as case-sensitive (@philsturgeon is that correct assumption?)
- [ ] the case, when a variable is a part of hostname, should be handled correctly: host can be compared case-insensitive while variable name should be compared case-sensitively

**Additional context**
This task is a followup for a discussion here: https://github.com/stoplightio/http-spec/pull/83#discussion_r389628980

**Comment by philsturgeon** [comment]
I don't have enough context to know if variable names should be case sensitive or not, I don't think it matters too much either way? Some people will expect it to work one way and others another.
